version: '1'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - 3000:3000
    volumes:
      - ./api/src:/app/src
      - ./api/package.json:/app/package.json
      - ./api/.env:/app/.env
volumes:
  mysql_data:
