version: '1'
services:

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: parking
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  app:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - 3000:3000
    volumes:
      - ./api/src:/app/src
      - ./api/package.json:/app/package.json
      - ./api/.env:/app/.env
volumes:
  mysql_data:
